-- =============================================================================
-- EXO-TRACE Supabase 版 データベース定義
--
--   エクソソーム製品の 入荷 → 受入検品 → 出荷（FEFO自動引当） → 返品 → ロット/顧客追跡 → 回収
--   をロット単位で管理する。業務ルールはすべてこのファイルの関数（RPC）に実装している。
--
-- 使い方（ターミナル不要）
--   1. Supabase ダッシュボード「SQL Editor」→「New query」にこのファイルの内容をすべて貼り付けて「Run」
--      （何度実行しても既存データは消えません。更新版を貼り直すときも同じ手順です）
--   2. 「Authentication」→「Users」→「Add user」→「Create new user」で利用者を作成（Auto Confirm User にチェック）
--   3. SQL Editor で、利用を許可するメールアドレスを登録する（人数分）
--        insert into exo.app_user (email) values ('taro@example.com');
--
-- 構成
--   exo スキーマ … テーブルと内部関数。API（PostgREST）には公開しない
--   public スキーマ … 画面から呼ぶ関数（RPC）だけを置く。ログイン済みかつ exo.app_user に登録された利用者のみ実行できる
--
-- 設計書との対応：詳細設計書 v1.3 の簡易版（段階導入）。発注・受注伝票、納品先、ロール別権限、
--   合格済ロットへの分納、温度記録、添付ファイルは本格版で実装する。
-- =============================================================================

create schema if not exists exo;
revoke all on schema exo from public;

-- -----------------------------------------------------------------------------
-- テーブル
-- -----------------------------------------------------------------------------

-- 利用を許可するユーザー（Supabase Auth のメールアドレス）
create table if not exists exo.app_user (
  email       text primary key check (email = lower(btrim(email)) and email like '%@%'),
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists exo.m_supplier (
  id            bigint generated by default as identity primary key,
  supplier_code text not null check (supplier_code ~ '^[A-Za-z0-9-]+$'),
  name          text not null check (name <> ''),
  contact_name  text,
  phone         text,
  email         text,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index if not exists m_supplier_code_uq on exo.m_supplier (upper(supplier_code));

create table if not exists exo.m_product (
  id                 bigint generated by default as identity primary key,
  product_code       text not null check (product_code ~ '^[A-Za-z0-9-]+$'),
  name               text not null check (name <> ''),
  storage_class      text not null check (storage_class in ('M80', 'M20', 'COLD', 'RT')),
  shelf_life_days    integer not null check (shelf_life_days > 0),
  min_remaining_days integer not null default 90 check (min_remaining_days >= 0),
  regulatory_class   text not null check (regulatory_class in ('COSMETIC_RAW', 'RESEARCH_USE', 'MEDICAL_USE', 'OTHER')),
  list_price         numeric(12, 2) check (list_price >= 0),
  reorder_point      integer check (reorder_point >= 0),
  is_active          boolean not null default true,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create unique index if not exists m_product_code_uq on exo.m_product (upper(product_code));

create table if not exists exo.m_customer (
  id                bigint generated by default as identity primary key,
  customer_code     text not null check (customer_code ~ '^[A-Za-z0-9-]+$'),
  name              text not null check (name <> ''),
  customer_type     text not null check (customer_type in ('MEDICAL', 'SALON', 'DISTRIBUTOR', 'RESEARCH', 'OTHER')),
  medical_inst_code text,
  address           text not null check (address <> ''),
  contact_name      text,
  phone             text,
  email             text,
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint m_customer_medical_code_ck check (customer_type <> 'MEDICAL' or coalesce(medical_inst_code, '') <> '')
);
create unique index if not exists m_customer_code_uq on exo.m_customer (upper(customer_code));

create table if not exists exo.m_location (
  id             bigint generated by default as identity primary key,
  location_code  text not null check (location_code ~ '^[A-Za-z0-9-]+$'),
  name           text not null check (name <> ''),
  storage_class  text not null check (storage_class in ('M80', 'M20', 'COLD', 'RT')),
  temp_min       numeric not null,
  temp_max       numeric not null,
  is_quarantine  boolean not null default false,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint m_location_temp_ck check (temp_min < temp_max)
);
create unique index if not exists m_location_code_uq on exo.m_location (upper(location_code));

-- 販売可否ルール（規制区分 × 顧客区分）
create table if not exists exo.m_sales_rule (
  id               bigint generated by default as identity primary key,
  regulatory_class text not null check (regulatory_class in ('COSMETIC_RAW', 'RESEARCH_USE', 'MEDICAL_USE', 'OTHER')),
  customer_type    text not null check (customer_type in ('MEDICAL', 'SALON', 'DISTRIBUTOR', 'RESEARCH', 'OTHER')),
  allowed          boolean not null default false,
  updated_at       timestamptz not null default now(),
  unique (regulatory_class, customer_type)
);

create table if not exists exo.t_lot (
  id              bigint generated by default as identity primary key,
  lot_no          text not null unique,
  product_id      bigint not null references exo.m_product (id),
  supplier_id     bigint not null references exo.m_supplier (id),
  supplier_lot_no text not null check (supplier_lot_no <> ''),
  manufactured_on date,
  expires_on      date not null,
  received_on     date not null,
  unit_cost       numeric(14, 2) not null default 0 check (unit_cost >= 0),
  status          text not null check (status in ('QUARANTINE', 'RELEASED', 'HOLD', 'REJECTED', 'RECALLED', 'EXPIRED', 'VOID')),
  status_reason   text,
  inspected_by    text,
  inspected_at    timestamptz,
  created_at      timestamptz not null default now(),
  unique (supplier_id, product_id, supplier_lot_no)
);
create index if not exists t_lot_product_idx on exo.t_lot (product_id);

create table if not exists exo.t_receipt (
  id              bigint generated by default as identity primary key,
  receipt_no      text not null unique,
  supplier_id     bigint not null references exo.m_supplier (id),
  receipt_date    date not null,
  product_id      bigint not null references exo.m_product (id),
  supplier_lot_no text not null,
  manufactured_on date,
  expires_on      date not null,
  arrival_temp    numeric,
  location_id     bigint not null references exo.m_location (id),
  quantity        integer not null check (quantity > 0),
  unit_price      numeric(14, 2) not null check (unit_price >= 0),
  lot_id          bigint not null references exo.t_lot (id),
  status          text not null default 'CONFIRMED' check (status in ('CONFIRMED')),
  created_at      timestamptz not null default now(),
  created_by      text not null
);
create index if not exists t_receipt_lot_idx on exo.t_receipt (lot_id);

-- 在庫（ロット × 保管場所）。必ず在庫移動履歴と同時に更新する（BR-02）
create table if not exists exo.t_inventory (
  id          bigint generated by default as identity primary key,
  lot_id      bigint not null references exo.t_lot (id),
  location_id bigint not null references exo.m_location (id),
  on_hand_qty integer not null default 0 check (on_hand_qty >= 0),
  unique (lot_id, location_id)
);
create index if not exists t_inventory_location_idx on exo.t_inventory (location_id);

create table if not exists exo.t_stock_movement (
  id            bigint generated by default as identity primary key,
  moved_at      timestamptz not null default now(),
  movement_type text not null check (movement_type in ('RECEIPT', 'SHIPMENT', 'CANCEL', 'RETURN', 'TRANSFER_IN', 'TRANSFER_OUT', 'DISPOSE', 'ADJUST', 'SUPPLIER_RETURN')),
  lot_id        bigint not null references exo.t_lot (id),
  location_id   bigint not null references exo.m_location (id),
  quantity      integer not null check (quantity <> 0),
  ref_type      text,
  ref_id        bigint,
  reason        text,
  created_by    text not null
);
create index if not exists t_stock_movement_lot_idx on exo.t_stock_movement (lot_id, location_id);

create table if not exists exo.t_shipment (
  id          bigint generated by default as identity primary key,
  shipment_no text not null unique,
  customer_id bigint not null references exo.m_customer (id),
  shipped_on  date not null,
  status      text not null check (status in ('SHIPPED', 'CANCELLED')),
  note        text,
  created_at  timestamptz not null default now(),
  created_by  text not null
);
create index if not exists t_shipment_customer_idx on exo.t_shipment (customer_id);

create table if not exists exo.t_shipment_line (
  id          bigint generated by default as identity primary key,
  shipment_id bigint not null references exo.t_shipment (id),
  product_id  bigint not null references exo.m_product (id),
  lot_id      bigint not null references exo.t_lot (id),
  location_id bigint not null references exo.m_location (id),
  quantity    integer not null check (quantity > 0),
  unit_price  numeric(14, 2) not null check (unit_price >= 0),
  unit_cost   numeric(14, 2) not null default 0,
  status      text not null check (status in ('SHIPPED', 'CANCELLED'))
);
create index if not exists t_shipment_line_shipment_idx on exo.t_shipment_line (shipment_id);
create index if not exists t_shipment_line_lot_idx on exo.t_shipment_line (lot_id);

create table if not exists exo.t_recall (
  id         bigint generated by default as identity primary key,
  recall_no  text not null unique,
  title      text not null,
  reason     text not null,
  severity   text not null check (severity in ('I', 'II', 'III')),
  started_on date not null,
  closed_on  date,
  status     text not null check (status in ('OPEN', 'IN_PROGRESS', 'CLOSED')),
  created_at timestamptz not null default now(),
  created_by text not null
);

create table if not exists exo.t_recall_lot (
  id        bigint generated by default as identity primary key,
  recall_id bigint not null references exo.t_recall (id),
  lot_id    bigint not null references exo.t_lot (id),
  unique (recall_id, lot_id)
);
create index if not exists t_recall_lot_lot_idx on exo.t_recall_lot (lot_id);

create table if not exists exo.t_recall_target (
  id                bigint generated by default as identity primary key,
  recall_id         bigint not null references exo.t_recall (id),
  customer_id       bigint not null references exo.m_customer (id),
  lot_id            bigint not null references exo.t_lot (id),
  shipped_qty       integer not null default 0 check (shipped_qty >= 0),
  recovered_qty     integer not null default 0 check (recovered_qty >= 0),
  unrecoverable_qty integer not null default 0 check (unrecoverable_qty >= 0),
  contacted_on      date,
  contact_method    text,
  status            text not null check (status in ('NOT_CONTACTED', 'CONTACTED', 'RECOVERED', 'CLOSED')),
  close_reason      text,
  updated_at        timestamptz not null default now(),
  unique (recall_id, customer_id, lot_id)
);

create table if not exists exo.t_return (
  id                  bigint generated by default as identity primary key,
  return_no           text not null unique,
  shipment_line_id    bigint not null references exo.t_shipment_line (id),
  recall_target_id    bigint references exo.t_recall_target (id),
  returned_on         date not null,
  quantity            integer not null check (quantity > 0),
  reason              text not null,
  disposition         text not null check (disposition in ('RESTOCK', 'DISPOSE')),
  location_id         bigint not null references exo.m_location (id),
  restock_location_id bigint references exo.m_location (id),
  created_at          timestamptz not null default now(),
  created_by          text not null,
  constraint t_return_restock_ck check ((disposition = 'RESTOCK') = (restock_location_id is not null))
);
create index if not exists t_return_line_idx on exo.t_return (shipment_line_id);
create index if not exists t_return_target_idx on exo.t_return (recall_target_id);

create table if not exists exo.t_lot_status_history (
  id          bigint generated by default as identity primary key,
  lot_id      bigint not null references exo.t_lot (id),
  from_status text,
  to_status   text not null,
  reason      text,
  changed_at  timestamptz not null default now(),
  changed_by  text not null
);
create index if not exists t_lot_status_history_lot_idx on exo.t_lot_status_history (lot_id);

-- 日次チェックの結果
create table if not exists exo.t_job_log (
  id      bigint generated by default as identity primary key,
  job     text not null,
  ran_at  timestamptz not null default now(),
  result  jsonb not null
);

-- API から直接は触れない（多重防御として RLS も有効化。ポリシーなし＝全拒否）
do $$
declare t text;
begin
  for t in select tablename from pg_tables where schemaname = 'exo' loop
    execute format('alter table exo.%I enable row level security', t);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 内部関数（exo スキーマ）
-- -----------------------------------------------------------------------------

/** コード定義（設計書「コード定義」シートと同じ値）。画面の選択肢の並び順を保つため json（順序保持）で持つ */
create or replace function exo.codes_json() returns json
language sql immutable set search_path = '' as $$
  select '{
    "storage_class": {"M80": "-80℃", "M20": "-20℃", "COLD": "2-8℃", "RT": "室温"},
    "regulatory_class": {"COSMETIC_RAW": "化粧品原料", "RESEARCH_USE": "研究用", "MEDICAL_USE": "医療機関向け", "OTHER": "その他"},
    "customer_type": {"MEDICAL": "医療機関", "SALON": "サロン", "DISTRIBUTOR": "代理店", "RESEARCH": "研究機関", "OTHER": "その他"},
    "lot_status": {"QUARANTINE": "検品待ち", "RELEASED": "合格", "HOLD": "保留", "REJECTED": "不合格", "RECALLED": "回収", "EXPIRED": "期限切れ", "VOID": "無効"},
    "target_status": {"NOT_CONTACTED": "未連絡", "CONTACTED": "連絡済", "RECOVERED": "回収済", "CLOSED": "クローズ"}
  }'::json
$$;

create or replace function exo.codes() returns jsonb
language sql immutable set search_path = '' as $$
  select exo.codes_json()::jsonb
$$;

create or replace function exo.code_label(p_type text, p_value text) returns text
language sql immutable set search_path = '' as $$
  select coalesce(exo.codes() -> p_type ->> p_value, p_value)
$$;

/** 業務日付（日本時間）。テスト用に設定 exo.today で固定できる（API からは設定できない） */
create or replace function exo.today() returns date
language sql stable set search_path = '' as $$
  select coalesce(nullif(current_setting('exo.today', true), '')::date, (now() at time zone 'Asia/Tokyo')::date)
$$;

create or replace function exo.fmt_ts(p_ts timestamptz) returns text
language sql stable set search_path = '' as $$
  select to_char(p_ts at time zone 'Asia/Tokyo', 'YYYY-MM-DD HH24:MI:SS')
$$;

/** 業務エラー（画面にそのまま表示する） */
create or replace function exo.fail(p_message text) returns void
language plpgsql volatile set search_path = '' as $$
begin
  raise exception using errcode = 'P0001', message = p_message;
end $$;

/** ログイン中の利用者（メールアドレス）。未ログイン・未許可ならエラー */
create or replace function exo.require_user() returns text
language plpgsql stable set search_path = '' as $$
declare
  v_email text := lower(btrim(coalesce(auth.jwt() ->> 'email', '')));
begin
  if auth.uid() is null or v_email = '' then
    raise exception using errcode = '42501', message = 'ログインしてください。';
  end if;
  if not exists (select 1 from exo.app_user u where u.email = v_email and u.is_active) then
    raise exception using errcode = '42501',
      message = 'このアカウント（' || v_email || '）には利用権限がありません。管理者に利用者登録を依頼してください。';
  end if;
  return v_email;
end $$;

/** 更新処理を1本ずつ実行する（設計書 P-00 の簡易版：全更新処理を直列化） */
create or replace function exo.write_lock() returns void
language sql volatile set search_path = '' as $$
  select pg_advisory_xact_lock(7428301)
$$;

-- ---- 入力値の取り出し（画面から来た JSON） ----

create or replace function exo.trim_text(p_value text) returns text
language sql immutable set search_path = '' as $$
  select nullif(btrim(p_value, E' \t\r\n' || chr(12288)), '')
$$;

/** 文字列（前後の空白を除去、空なら null） */
create or replace function exo.j_text(p jsonb, k text) returns text
language sql immutable set search_path = '' as $$
  select case when p is null or jsonb_typeof(p) <> 'object' or jsonb_typeof(p -> k) is null or jsonb_typeof(p -> k) = 'null' then null
              else exo.trim_text(p ->> k) end
$$;

/** 数値（未入力は null、数値でなければ NaN） */
create or replace function exo.j_num(p jsonb, k text) returns numeric
language plpgsql immutable set search_path = '' as $$
declare v text := exo.j_text(p, k);
begin
  if v is null then return null; end if;
  if v !~ '^[-+]?(\d+\.?\d*|\.\d+)([eE][-+]?\d+)?$' or length(v) > 30 then return 'NaN'; end if;
  return v::numeric;
exception when others then
  return 'NaN';
end $$;

/** ID（数字でなければ null） */
create or replace function exo.j_id(p jsonb, k text) returns bigint
language sql immutable set search_path = '' as $$
  select case when exo.j_text(p, k) ~ '^\d{1,18}$' then exo.j_text(p, k)::bigint end
$$;

create or replace function exo.j_bool(p jsonb, k text) returns boolean
language sql immutable set search_path = '' as $$
  select coalesce(lower(exo.j_text(p, k)) in ('true', '1'), false)
$$;

/** YYYY-MM-DD の日付（不正なら null） */
create or replace function exo.to_date(p_text text) returns date
language plpgsql immutable set search_path = '' as $$
begin
  if p_text is null or p_text !~ '^\d{4}-\d{2}-\d{2}$' then return null; end if;
  return p_text::date;
exception when others then
  return null;
end $$;

/** 1以上の整数 */
create or replace function exo.pos_int(p_value numeric, p_label text) returns integer
language plpgsql immutable set search_path = '' as $$
begin
  if p_value is null or p_value = 'NaN' or p_value <= 0 or p_value <> trunc(p_value) or p_value > 1000000000 then
    perform exo.fail(p_label || 'は1以上の整数で入力してください。');
  end if;
  return p_value::integer;
end $$;

/** 伝票番号 例: SH-202610-0001 */
create or replace function exo.next_no(p_prefix text, p_date date, p_existing text[]) returns text
language sql immutable set search_path = '' as $$
  select p_prefix || '-' || to_char(p_date, 'YYYYMM') || '-' || lpad((coalesce(max(substr(n, length(p_prefix) + 9)::integer), 0) + 1)::text, 4, '0')
  from unnest(p_existing) n
  where n like p_prefix || '-' || to_char(p_date, 'YYYYMM') || '-%' and substr(n, length(p_prefix) + 9) ~ '^\d+$'
$$;

/** 在庫を増減し、在庫移動履歴を記録する（BR-02：在庫は必ず移動履歴と一緒に更新） */
create or replace function exo.move(p_type text, p_lot_id bigint, p_location_id bigint, p_qty integer,
  p_ref_type text, p_ref_id bigint, p_reason text, p_by text) returns void
language plpgsql volatile set search_path = '' as $$
declare v_cur integer;
begin
  select on_hand_qty into v_cur from exo.t_inventory where lot_id = p_lot_id and location_id = p_location_id for update;
  if coalesce(v_cur, 0) + p_qty < 0 then
    perform exo.fail('在庫が不足しています（ロット ' || coalesce((select lot_no from exo.t_lot where id = p_lot_id), p_lot_id::text) ||
      '、保管場所 ' || coalesce((select name from exo.m_location where id = p_location_id), p_location_id::text) || '）。');
  end if;
  insert into exo.t_inventory (lot_id, location_id, on_hand_qty) values (p_lot_id, p_location_id, coalesce(v_cur, 0) + p_qty)
  on conflict (lot_id, location_id) do update set on_hand_qty = excluded.on_hand_qty;
  insert into exo.t_stock_movement (movement_type, lot_id, location_id, quantity, ref_type, ref_id, reason, created_by)
  values (p_type, p_lot_id, p_location_id, p_qty, p_ref_type, p_ref_id, p_reason, p_by);
end $$;

create or replace function exo.set_lot_status(p_lot_id bigint, p_to text, p_reason text, p_by text) returns void
language plpgsql volatile set search_path = '' as $$
declare v_from text;
begin
  select status into v_from from exo.t_lot where id = p_lot_id for update;
  update exo.t_lot set status = p_to, status_reason = p_reason where id = p_lot_id;
  insert into exo.t_lot_status_history (lot_id, from_status, to_status, reason, changed_by)
  values (p_lot_id, v_from, p_to, p_reason, p_by);
end $$;

/** 出荷明細の返品数量。p_recall: null=すべて、true=回収品のみ、false=通常返品のみ */
create or replace function exo.returned_qty(p_line_id bigint, p_recall boolean default null) returns integer
language sql stable set search_path = '' as $$
  select coalesce(sum(r.quantity), 0)::integer from exo.t_return r
  where r.shipment_line_id = p_line_id
    and (p_recall is null or (p_recall and r.recall_target_id is not null) or (not p_recall and r.recall_target_id is null))
$$;

/** ロットが対象になっている未完了の回収案件 */
create or replace function exo.open_recall_ids(p_lot_id bigint) returns setof bigint
language sql stable set search_path = '' as $$
  select rl.recall_id from exo.t_recall_lot rl join exo.t_recall r on r.id = rl.recall_id
  where rl.lot_id = p_lot_id and r.status <> 'CLOSED' order by rl.recall_id
$$;

/** ロットの表示用データ（在庫＝全保管場所、availableStock＝隔離保管場所を除く） */
drop view if exists exo.v_lot;
create view exo.v_lot as
select l.id, l.status, l.product_id, l.expires_on, l.received_on,
  (l.expires_on - exo.today()) as days_left,
  coalesce(inv.stock, 0)::integer as stock,
  coalesce(inv.avail, 0)::integer as available_stock,
  jsonb_build_object(
    'id', l.id, 'lot_no', l.lot_no, 'supplier_lot_no', l.supplier_lot_no, 'product_id', l.product_id,
    'product', p.name, 'product_code', p.product_code, 'supplier', s.name,
    'manufactured_on', l.manufactured_on, 'expires_on', l.expires_on, 'received_on', l.received_on,
    'daysLeft', l.expires_on - exo.today(), 'unit_cost', l.unit_cost,
    'status', l.status, 'statusLabel', exo.code_label('lot_status', l.status), 'status_reason', l.status_reason,
    'inspected_at', exo.fmt_ts(l.inspected_at),
    'stock', coalesce(inv.stock, 0), 'availableStock', coalesce(inv.avail, 0)) as j
from exo.t_lot l
join exo.m_product p on p.id = l.product_id
join exo.m_supplier s on s.id = l.supplier_id
left join lateral (
  select sum(i.on_hand_qty) as stock, sum(i.on_hand_qty) filter (where not loc.is_quarantine) as avail
  from exo.t_inventory i join exo.m_location loc on loc.id = i.location_id
  where i.lot_id = l.id
) inv on true;
revoke all on exo.v_lot from public;

create or replace function exo.lot_view(p_lot_id bigint) returns jsonb
language sql stable set search_path = '' as $$
  select j from exo.v_lot where id = p_lot_id
$$;

create or replace function exo.shipment_view(p_shipment_id bigint) returns jsonb
language sql stable set search_path = '' as $$
  with lines as (
    select sl.id, jsonb_build_object(
        'id', sl.id, 'product', p.name, 'lot_no', l.lot_no, 'expires_on', l.expires_on,
        'lot_status', exo.code_label('lot_status', l.status), 'lot_status_code', l.status,
        'quantity', sl.quantity, 'unit_price', sl.unit_price, 'returned', exo.returned_qty(sl.id),
        'returnable', case when sl.status = 'SHIPPED' then sl.quantity - exo.returned_qty(sl.id) else 0 end,
        'status', sl.status) as j,
      sl.quantity * sl.unit_price as amount
    from exo.t_shipment_line sl
    join exo.t_lot l on l.id = sl.lot_id
    join exo.m_product p on p.id = sl.product_id
    where sl.shipment_id = p_shipment_id
  )
  select jsonb_build_object(
    'id', s.id, 'shipment_no', s.shipment_no, 'customer', c.name, 'customer_id', s.customer_id,
    'shipped_on', s.shipped_on, 'status', s.status, 'note', s.note,
    'lines', coalesce((select jsonb_agg(j order by id) from lines), '[]'::jsonb),
    'amount', coalesce((select sum(amount) from lines), 0))
  from exo.t_shipment s join exo.m_customer c on c.id = s.customer_id
  where s.id = p_shipment_id
$$;

create or replace function exo.recall_view(p_recall_id bigint) returns jsonb
language sql stable set search_path = '' as $$
  with t as (
    select rt.*, c.name as customer, c.customer_code, c.contact_name, c.phone, c.email, l.lot_no
    from exo.t_recall_target rt
    join exo.m_customer c on c.id = rt.customer_id
    join exo.t_lot l on l.id = rt.lot_id
    where rt.recall_id = p_recall_id
  ), act as (select * from t where shipped_qty > 0)
  select jsonb_build_object(
    'id', r.id, 'recall_no', r.recall_no, 'title', r.title, 'reason', r.reason, 'severity', r.severity,
    'started_on', r.started_on, 'closed_on', r.closed_on, 'status', r.status,
    'lots', coalesce((select jsonb_agg(l.lot_no order by l.lot_no) from exo.t_recall_lot rl join exo.t_lot l on l.id = rl.lot_id
                      where rl.recall_id = r.id), '[]'::jsonb),
    'targets', coalesce((select jsonb_agg(jsonb_build_object(
        'id', t.id, 'recall_id', t.recall_id, 'customer_id', t.customer_id, 'lot_id', t.lot_id,
        'shipped_qty', t.shipped_qty, 'recovered_qty', t.recovered_qty, 'unrecoverable_qty', t.unrecoverable_qty,
        'contacted_on', t.contacted_on, 'contact_method', t.contact_method, 'status', t.status, 'close_reason', t.close_reason,
        'customer', t.customer, 'customer_code', t.customer_code, 'contact_name', t.contact_name, 'phone', t.phone,
        'email', t.email, 'lot_no', t.lot_no, 'statusLabel', exo.code_label('target_status', t.status)) order by t.id) from t), '[]'::jsonb),
    'contactedRate', case when (select count(*) from act) = 0 then 100
      else round(100.0 * (select count(*) from act where status <> 'NOT_CONTACTED') / (select count(*) from act)) end,
    'recoveredRate', case when coalesce((select sum(shipped_qty) from act), 0) = 0 then 100
      else round(100.0 * (select sum(least(shipped_qty, recovered_qty + unrecoverable_qty)) from act) / (select sum(shipped_qty) from act)) end,
    'remainingStock', coalesce((select sum(i.on_hand_qty) from exo.t_recall_lot rl join exo.t_inventory i on i.lot_id = rl.lot_id
                               where rl.recall_id = r.id), 0))
  from exo.t_recall r where r.id = p_recall_id
$$;

/** 回収対象の抽出（SQL-03 相当。何度実行しても同じ結果） */
create or replace function exo.extract_targets(p_recall_id bigint) returns void
language plpgsql volatile set search_path = '' as $$
declare
  v_status text;
  rec record;
begin
  select status into v_status from exo.t_recall where id = p_recall_id for update;
  if v_status is null or v_status = 'CLOSED' then return; end if;
  for rec in
    with net as (  -- 顧客 × ロットの出荷正味数量（出荷 − 通常返品）
      select s.customer_id, sl.lot_id, sum(sl.quantity - exo.returned_qty(sl.id, false))::integer as qty
      from exo.t_shipment_line sl
      join exo.t_shipment s on s.id = sl.shipment_id
      where sl.status = 'SHIPPED' and sl.lot_id in (select lot_id from exo.t_recall_lot where recall_id = p_recall_id)
      group by s.customer_id, sl.lot_id
    )
    select coalesce(n.customer_id, t.customer_id) as customer_id, coalesce(n.lot_id, t.lot_id) as lot_id,
      coalesce(n.qty, 0) as qty, t.id as target_id, t.recovered_qty, t.unrecoverable_qty, t.status
    from net n
    full join (select * from exo.t_recall_target where recall_id = p_recall_id) t
      on t.customer_id = n.customer_id and t.lot_id = n.lot_id
  loop
    if rec.target_id is null then
      insert into exo.t_recall_target (recall_id, customer_id, lot_id, shipped_qty, status, close_reason)
      values (p_recall_id, rec.customer_id, rec.lot_id, rec.qty,
        case when rec.qty > 0 then 'NOT_CONTACTED' else 'CLOSED' end,
        case when rec.qty > 0 then null else '自動：出荷正味0' end);
    elsif rec.qty = 0 and rec.recovered_qty = 0 then
      update exo.t_recall_target set shipped_qty = 0, unrecoverable_qty = 0, status = 'CLOSED', close_reason = '自動：出荷正味0', updated_at = now()
      where id = rec.target_id;
    else
      update exo.t_recall_target set shipped_qty = rec.qty,
        unrecoverable_qty = least(unrecoverable_qty, greatest(rec.qty - recovered_qty, 0)),
        status = case when status = 'CLOSED' then status
                      when recovered_qty + least(unrecoverable_qty, greatest(rec.qty - recovered_qty, 0)) >= rec.qty then 'RECOVERED'
                      when status = 'RECOVERED' then case when contacted_on is not null then 'CONTACTED' else 'NOT_CONTACTED' end
                      else status end,
        updated_at = now()
      where id = rec.target_id;
    end if;
  end loop;
  if v_status = 'OPEN' then
    update exo.t_recall set status = 'IN_PROGRESS' where id = p_recall_id;
  end if;
end $$;

/** 日次チェック（B-01 期限切れ判定 ／ B-03 在庫整合性チェック）。pg_cron で毎日 1:00（日本時間）に実行 */
create or replace function exo.daily_check() returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_today date := exo.today();
  v_expired jsonb := '[]';
  v_mismatch jsonb;
  v_result jsonb;
  rec record;
begin
  perform exo.write_lock();
  for rec in select id, lot_no from exo.t_lot
             where status in ('RELEASED', 'HOLD') and expires_on < v_today order by expires_on, id for update loop
    perform exo.set_lot_status(rec.id, 'EXPIRED', '期限到来（日次チェック）', 'system');
    v_expired := v_expired || to_jsonb(rec.lot_no);
  end loop;
  select coalesce(jsonb_agg(jsonb_build_object('lot_no', l.lot_no, 'location', loc.name,
           'on_hand', x.on_hand, 'movement_total', x.moved) order by l.lot_no, loc.name), '[]'::jsonb)
  into v_mismatch
  from (
    select coalesce(i.lot_id, m.lot_id) as lot_id, coalesce(i.location_id, m.location_id) as location_id,
      coalesce(i.on_hand_qty, 0) as on_hand, coalesce(m.total, 0) as moved
    from exo.t_inventory i
    full join (select lot_id, location_id, sum(quantity) as total from exo.t_stock_movement group by lot_id, location_id) m
      on m.lot_id = i.lot_id and m.location_id = i.location_id
    where coalesce(i.on_hand_qty, 0) <> coalesce(m.total, 0)
  ) x
  join exo.t_lot l on l.id = x.lot_id
  join exo.m_location loc on loc.id = x.location_id;
  v_result := jsonb_build_object('expired', v_expired, 'mismatches', v_mismatch);
  insert into exo.t_job_log (job, result) values ('daily_check', v_result);
  delete from exo.t_job_log where job = 'daily_check' and ran_at < now() - interval '400 days';
  return v_result;
end $$;
revoke all on function exo.daily_check() from public;

-- -----------------------------------------------------------------------------
-- 画面から呼ぶ関数（public スキーマ = Supabase の API で公開される）
--   すべて p jsonb を1つ受け取り jsonb を返す。security definer で exo のテーブルを操作し、
--   最初に exo.require_user() でログインと利用許可を確認する。
-- -----------------------------------------------------------------------------

-- 更新版を貼り直したときに戻り値の型が変わっても置き換えられるよう、いったん削除して作り直す
do $$
declare f regprocedure;
begin
  for f in select p.oid::regprocedure from pg_proc p
           where p.pronamespace = 'public'::regnamespace and p.proname = any (array['get_config', 'get_masters', 'get_dashboard',
             'get_lots', 'get_inventory', 'get_recent_shipments', 'get_shipment_by_no', 'save_master', 'save_sales_rule',
             'register_receipt', 'change_lot_status', 'create_shipment', 'cancel_shipment', 'register_return', 'trace_lot',
             'trace_customer', 'create_recall', 'list_recalls', 'reextract_recall', 'update_recall_target', 'close_recall'])
  loop
    execute 'drop function ' || f;
  end loop;
end $$;

create or replace function public.get_config(p jsonb default '{}') returns json
language plpgsql stable security definer set search_path = '' as $$
declare v_user text := exo.require_user();
begin
  return json_build_object('codes', exo.codes_json(), 'today', exo.today(), 'user', v_user);
end $$;

create or replace function public.get_masters(p jsonb default '{}') returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  perform exo.require_user();
  return jsonb_build_object(
    'suppliers', coalesce((select jsonb_agg(to_jsonb(x) - 'created_at' - 'updated_at' order by x.id) from exo.m_supplier x), '[]'),
    'products', coalesce((select jsonb_agg(to_jsonb(x) - 'created_at' - 'updated_at' order by x.id) from exo.m_product x), '[]'),
    'customers', coalesce((select jsonb_agg(to_jsonb(x) - 'created_at' - 'updated_at' order by x.id) from exo.m_customer x), '[]'),
    'locations', coalesce((select jsonb_agg(to_jsonb(x) - 'created_at' - 'updated_at' order by x.id) from exo.m_location x), '[]'),
    'salesRules', coalesce((select jsonb_agg(to_jsonb(x) - 'updated_at' order by x.id) from exo.m_sales_rule x), '[]'));
end $$;

create or replace function public.get_dashboard(p jsonb default '{}') returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_today date := exo.today();
begin
  perform exo.require_user();
  return jsonb_build_object(
    'expiringSoon', coalesce((select jsonb_agg(j order by days_left, id) from exo.v_lot
      where stock > 0 and expires_on >= v_today and days_left <= 90 and status in ('RELEASED', 'HOLD', 'QUARANTINE')), '[]'),
    'expired', coalesce((select jsonb_agg(j order by expires_on, id) from exo.v_lot
      where stock > 0 and (status = 'EXPIRED' or expires_on < v_today)), '[]'),
    'quarantine', coalesce((select jsonb_agg(j order by expires_on, id) from exo.v_lot where status = 'QUARANTINE'), '[]'),
    'hold', coalesce((select jsonb_agg(j order by expires_on, id) from exo.v_lot where stock > 0 and status = 'HOLD'), '[]'),
    'lowStock', coalesce((select jsonb_agg(jsonb_build_object('product', x.name, 'available', x.available, 'reorderPoint', x.reorder_point) order by x.id)
      from (select pr.id, pr.name, pr.reorder_point,
              coalesce((select sum(v.available_stock) from exo.v_lot v where v.product_id = pr.id and v.status = 'RELEASED' and v.stock > 0), 0) as available
            from exo.m_product pr where pr.is_active and coalesce(pr.reorder_point, 0) > 0) x
      where x.available <= x.reorder_point), '[]'),
    'recalls', coalesce((select jsonb_agg(exo.recall_view(r.id) order by r.id) from exo.t_recall r where r.status <> 'CLOSED'), '[]'),
    'lastCheck', (select jsonb_build_object('ran_at', exo.fmt_ts(j.ran_at)) || j.result from exo.t_job_log j
                  where j.job = 'daily_check' order by j.ran_at desc, j.id desc limit 1));
end $$;

/** p = { statuses: [...] }（空なら全件） */
create or replace function public.get_lots(p jsonb default '{}') returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_statuses text[];
begin
  perform exo.require_user();
  if jsonb_typeof(p -> 'statuses') = 'array' then
    select array_agg(x) into v_statuses from jsonb_array_elements_text(p -> 'statuses') x;
  end if;
  return coalesce((select jsonb_agg(j order by expires_on, id) from exo.v_lot
    where v_statuses is null or status = any (v_statuses)), '[]');
end $$;

create or replace function public.get_inventory(p jsonb default '{}') returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_today date := exo.today();
begin
  perform exo.require_user();
  return coalesce((select jsonb_agg(jsonb_build_object(
      'product', pr.name, 'product_code', pr.product_code, 'lot_no', l.lot_no, 'supplier_lot_no', l.supplier_lot_no,
      'location', loc.name, 'quarantine', loc.is_quarantine, 'expires_on', l.expires_on, 'daysLeft', l.expires_on - v_today,
      'status', l.status, 'statusLabel', exo.code_label('lot_status', l.status), 'qty', i.on_hand_qty,
      'allocatable', l.status = 'RELEASED' and not loc.is_quarantine and l.expires_on - v_today >= pr.min_remaining_days)
      order by pr.product_code, l.expires_on, l.id, loc.id)
    from exo.t_inventory i
    join exo.t_lot l on l.id = i.lot_id
    join exo.m_product pr on pr.id = l.product_id
    join exo.m_location loc on loc.id = i.location_id
    where i.on_hand_qty <> 0), '[]');
end $$;

/** p = { limit } */
create or replace function public.get_recent_shipments(p jsonb default '{}') returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_limit integer := least(greatest(coalesce(exo.j_id(p, 'limit'), 30), 1), 200);
begin
  perform exo.require_user();
  return coalesce((select jsonb_agg(exo.shipment_view(s.id) order by s.id desc)
    from (select id from exo.t_shipment order by id desc limit v_limit) s), '[]');
end $$;

/** p = { no } */
create or replace function public.get_shipment_by_no(p jsonb default '{}') returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_no text := upper(coalesce(exo.j_text(p, 'no'), ''));
  v_id bigint;
begin
  perform exo.require_user();
  if v_no = '' then perform exo.fail('出荷番号を入力してください。'); end if;
  select id into v_id from exo.t_shipment where upper(shipment_no) = v_no;
  if v_id is null then perform exo.fail('出荷番号「' || exo.j_text(p, 'no') || '」が見つかりません。'); end if;
  return exo.shipment_view(v_id);
end $$;

-- ---- マスタ ----

/** p = { table: 'm_supplier' | 'm_product' | 'm_customer' | 'm_location', data: {...} } */
create or replace function public.save_master(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_table text := exo.j_text(p, 'table');
  d jsonb := coalesce(p -> 'data', '{}');
  v_id bigint;
  v_code text;
  v_name text := exo.j_text(d, 'name');
  v_active boolean := case when exo.j_text(d, 'is_active') is null then true else exo.j_bool(d, 'is_active') end;
  v_n1 numeric; v_n2 numeric; v_n3 numeric; v_n4 numeric;
  v_type text; v_class text; v_reg text;
  v_has_stock boolean;
  v_row jsonb;
begin
  perform exo.require_user();
  perform exo.write_lock();
  if v_table is null or v_table not in ('m_supplier', 'm_product', 'm_customer', 'm_location') then
    perform exo.fail('更新できないテーブルです: ' || coalesce(v_table, ''));
  end if;
  v_code := exo.j_text(d, replace(v_table, 'm_', '') || '_code');
  if exo.j_text(d, 'id') is not null then
    v_id := exo.j_id(d, 'id');
    if v_id is null then perform exo.fail('データが見つかりません。画面を再読込してください。'); end if;
  end if;
  if v_code is null or v_name is null then perform exo.fail('コードと名称は必須です。'); end if;
  if v_code !~ '^[A-Za-z0-9-]+$' then perform exo.fail('コードは英数字とハイフンのみ使用できます。'); end if;

  if v_table = 'm_supplier' then
    if exists (select 1 from exo.m_supplier where upper(supplier_code) = upper(v_code) and id is distinct from v_id) then
      perform exo.fail('コード「' || v_code || '」は既に使われています。');
    end if;
    if v_id is null then
      insert into exo.m_supplier (supplier_code, name, contact_name, phone, email, is_active)
      values (v_code, v_name, exo.j_text(d, 'contact_name'), exo.j_text(d, 'phone'), exo.j_text(d, 'email'), v_active)
      returning to_jsonb(m_supplier.*) into v_row;
    else
      update exo.m_supplier set supplier_code = v_code, name = v_name, contact_name = exo.j_text(d, 'contact_name'),
        phone = exo.j_text(d, 'phone'), email = exo.j_text(d, 'email'), is_active = v_active, updated_at = now()
      where id = v_id returning to_jsonb(m_supplier.*) into v_row;
    end if;

  elsif v_table = 'm_product' then
    if exists (select 1 from exo.m_product where upper(product_code) = upper(v_code) and id is distinct from v_id) then
      perform exo.fail('コード「' || v_code || '」は既に使われています。');
    end if;
    v_class := exo.j_text(d, 'storage_class');
    v_reg := exo.j_text(d, 'regulatory_class');
    if v_class is null or not (exo.codes() -> 'storage_class' ? v_class) then perform exo.fail('保管温度区分を選択してください。'); end if;
    if v_reg is null or not (exo.codes() -> 'regulatory_class' ? v_reg) then perform exo.fail('規制区分を選択してください。'); end if;
    v_n1 := exo.j_num(d, 'shelf_life_days');
    if v_n1 is null or v_n1 = 'NaN' or v_n1 <= 0 or v_n1 <> trunc(v_n1) or v_n1 > 36500 then
      perform exo.fail('有効期間（日）を1以上の整数で入力してください。');
    end if;
    v_n2 := coalesce(exo.j_num(d, 'min_remaining_days'), 90);
    if v_n2 = 'NaN' or v_n2 < 0 or v_n2 <> trunc(v_n2) or v_n2 > 36500 then perform exo.fail('最低出荷残期間（日）は0以上の整数で入力してください。'); end if;
    v_n3 := exo.j_num(d, 'list_price');
    if v_n3 = 'NaN' or v_n3 < 0 or v_n3 >= 10000000000 then perform exo.fail('標準売価は0以上の数値で入力してください。'); end if;
    v_n4 := exo.j_num(d, 'reorder_point');
    if v_n4 = 'NaN' or v_n4 < 0 or v_n4 <> trunc(v_n4) or v_n4 > 1000000000 then perform exo.fail('発注点は0以上の整数で入力してください。'); end if;
    if v_id is not null and exists (select 1 from exo.m_product where id = v_id and storage_class <> v_class)
       and exists (select 1 from exo.t_inventory i join exo.t_lot l on l.id = i.lot_id where l.product_id = v_id and i.on_hand_qty > 0) then
      perform exo.fail('在庫がある商品の保管温度区分は変更できません。');
    end if;
    if v_id is null then
      insert into exo.m_product (product_code, name, storage_class, shelf_life_days, min_remaining_days, regulatory_class, list_price, reorder_point, is_active)
      values (v_code, v_name, v_class, v_n1, v_n2, v_reg, round(v_n3, 2), v_n4, v_active)
      returning to_jsonb(m_product.*) into v_row;
    else
      update exo.m_product set product_code = v_code, name = v_name, storage_class = v_class, shelf_life_days = v_n1,
        min_remaining_days = v_n2, regulatory_class = v_reg, list_price = round(v_n3, 2), reorder_point = v_n4,
        is_active = v_active, updated_at = now()
      where id = v_id returning to_jsonb(m_product.*) into v_row;
    end if;

  elsif v_table = 'm_customer' then
    if exists (select 1 from exo.m_customer where upper(customer_code) = upper(v_code) and id is distinct from v_id) then
      perform exo.fail('コード「' || v_code || '」は既に使われています。');
    end if;
    v_type := exo.j_text(d, 'customer_type');
    if v_type is null or not (exo.codes() -> 'customer_type' ? v_type) then perform exo.fail('顧客区分を選択してください。'); end if;
    if v_type = 'MEDICAL' and exo.j_text(d, 'medical_inst_code') is null then
      perform exo.fail('医療機関の場合、医療機関コードは必須です（BR-10）。');
    end if;
    if exo.j_text(d, 'address') is null then perform exo.fail('住所は必須です。'); end if;
    if v_id is null then
      insert into exo.m_customer (customer_code, name, customer_type, medical_inst_code, address, contact_name, phone, email, is_active)
      values (v_code, v_name, v_type, exo.j_text(d, 'medical_inst_code'), exo.j_text(d, 'address'), exo.j_text(d, 'contact_name'),
        exo.j_text(d, 'phone'), exo.j_text(d, 'email'), v_active)
      returning to_jsonb(m_customer.*) into v_row;
    else
      update exo.m_customer set customer_code = v_code, name = v_name, customer_type = v_type,
        medical_inst_code = exo.j_text(d, 'medical_inst_code'), address = exo.j_text(d, 'address'),
        contact_name = exo.j_text(d, 'contact_name'), phone = exo.j_text(d, 'phone'), email = exo.j_text(d, 'email'),
        is_active = v_active, updated_at = now()
      where id = v_id returning to_jsonb(m_customer.*) into v_row;
    end if;

  else -- m_location
    if exists (select 1 from exo.m_location where upper(location_code) = upper(v_code) and id is distinct from v_id) then
      perform exo.fail('コード「' || v_code || '」は既に使われています。');
    end if;
    v_class := exo.j_text(d, 'storage_class');
    if v_class is null or not (exo.codes() -> 'storage_class' ? v_class) then perform exo.fail('保管温度区分を選択してください。'); end if;
    v_n1 := exo.j_num(d, 'temp_min');
    v_n2 := exo.j_num(d, 'temp_max');
    if v_n1 is null or v_n2 is null or v_n1 = 'NaN' or v_n2 = 'NaN' or not (v_n1 < v_n2) or abs(v_n1) > 1000 or abs(v_n2) > 1000 then
      perform exo.fail('許容温度は 下限 < 上限 で入力してください。');
    end if;
    if v_id is not null then
      v_has_stock := exists (select 1 from exo.t_inventory where location_id = v_id and on_hand_qty > 0);
      if v_has_stock and not v_active then perform exo.fail('在庫がある保管場所は無効化できません。'); end if;
      if v_has_stock and exists (select 1 from exo.m_location where id = v_id
          and (storage_class <> v_class or is_quarantine <> exo.j_bool(d, 'is_quarantine'))) then
        perform exo.fail('在庫がある保管場所は、保管温度区分と隔離区分を変更できません。');
      end if;
    end if;
    if v_id is null then
      insert into exo.m_location (location_code, name, storage_class, temp_min, temp_max, is_quarantine, is_active)
      values (v_code, v_name, v_class, v_n1, v_n2, exo.j_bool(d, 'is_quarantine'), v_active)
      returning to_jsonb(m_location.*) into v_row;
    else
      update exo.m_location set location_code = v_code, name = v_name, storage_class = v_class, temp_min = v_n1, temp_max = v_n2,
        is_quarantine = exo.j_bool(d, 'is_quarantine'), is_active = v_active, updated_at = now()
      where id = v_id returning to_jsonb(m_location.*) into v_row;
    end if;
  end if;

  if v_row is null then perform exo.fail('データが見つかりません。画面を再読込してください。'); end if;
  return v_row - 'created_at' - 'updated_at';
end $$;

/** p = { regulatoryClass, customerType, allowed } */
create or replace function public.save_sales_rule(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_rc text := exo.j_text(p, 'regulatoryClass');
  v_ct text := exo.j_text(p, 'customerType');
begin
  perform exo.require_user();
  perform exo.write_lock();
  if v_rc is null or not (exo.codes() -> 'regulatory_class' ? v_rc) or v_ct is null or not (exo.codes() -> 'customer_type' ? v_ct) then
    perform exo.fail('規制区分または顧客区分が不正です。');
  end if;
  insert into exo.m_sales_rule (regulatory_class, customer_type, allowed) values (v_rc, v_ct, exo.j_bool(p, 'allowed'))
  on conflict (regulatory_class, customer_type) do update set allowed = excluded.allowed, updated_at = now();
  return 'true'::jsonb;
end $$;

-- ---- 入荷・検品（P-01 / P-02 / P-15 の簡易版） ----

/** p = { supplierId, productId, supplierLotNo, receiptDate, manufacturedOn, expiresOn, quantity, unitPrice, arrivalTemp, locationId } */
create or replace function public.register_receipt(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_user text := exo.require_user();
  v_today date := exo.today();
  v_product exo.m_product;
  v_supplier exo.m_supplier;
  v_loc exo.m_location;
  v_lot exo.t_lot;
  v_qty integer;
  v_price numeric := exo.j_num(p, 'unitPrice');
  v_temp numeric := exo.j_num(p, 'arrivalTemp');
  v_sup_lot text := exo.j_text(p, 'supplierLotNo');
  v_date date := exo.to_date(exo.j_text(p, 'receiptDate'));
  v_mfg date := exo.to_date(exo.j_text(p, 'manufacturedOn'));
  v_exp date;
  v_stock integer;
  v_head text;
  v_receipt_id bigint;
  v_receipt_no text;
  v_warning text := '';
begin
  perform exo.write_lock();
  select * into v_product from exo.m_product where id = exo.j_id(p, 'productId');
  if v_product.id is null then perform exo.fail('商品が見つかりません。画面を再読込してください。'); end if;
  select * into v_supplier from exo.m_supplier where id = exo.j_id(p, 'supplierId');
  if v_supplier.id is null then perform exo.fail('仕入先が見つかりません。画面を再読込してください。'); end if;
  select * into v_loc from exo.m_location where id = exo.j_id(p, 'locationId');
  if v_loc.id is null then perform exo.fail('保管場所が見つかりません。画面を再読込してください。'); end if;
  if not v_product.is_active then perform exo.fail('商品「' || v_product.name || '」は無効化されています。'); end if;
  if not v_supplier.is_active then perform exo.fail('仕入先「' || v_supplier.name || '」は無効化されています。'); end if;
  v_qty := exo.pos_int(exo.j_num(p, 'quantity'), '入荷数量');
  if v_price is null or v_price = 'NaN' or v_price < 0 or v_price >= 1000000000000 then
    perform exo.fail('仕入単価は0以上で入力してください。');
  end if;
  v_price := round(v_price, 2);
  if v_sup_lot is null then perform exo.fail('仕入先ロット番号を入力してください。'); end if;
  if length(v_sup_lot) > 100 then perform exo.fail('仕入先ロット番号は100文字以内で入力してください。'); end if;
  if v_date is null or v_date > v_today then perform exo.fail('入荷日は当日以前の日付を入力してください。'); end if;
  if exo.j_text(p, 'manufacturedOn') is not null and (v_mfg is null or v_mfg > v_date) then
    perform exo.fail('製造日は入荷日以前の日付を入力してください。');
  end if;
  if exo.j_text(p, 'expiresOn') is not null then
    v_exp := exo.to_date(exo.j_text(p, 'expiresOn'));
  elsif v_mfg is not null then
    v_exp := v_mfg + v_product.shelf_life_days;
  end if;
  if v_exp is null then perform exo.fail('使用期限を入力してください（製造日が不明な場合は必須）。'); end if;
  if v_exp <= v_date then perform exo.fail('使用期限は入荷日より後の日付を入力してください。'); end if;
  if v_temp = 'NaN' or abs(v_temp) > 1000 then perform exo.fail('到着時温度は数値（℃）で入力してください。'); end if;
  if v_loc.storage_class <> v_product.storage_class or v_loc.is_quarantine or not v_loc.is_active then
    perform exo.fail('保管場所「' || v_loc.name || '」には入庫できません（温度区分が商品と異なるか、隔離保管場所です）。');
  end if;

  select * into v_lot from exo.t_lot
  where supplier_id = v_supplier.id and product_id = v_product.id and supplier_lot_no = v_sup_lot for update;
  if v_lot.id is not null then
    if v_lot.expires_on <> v_exp then
      perform exo.fail('仕入先ロット番号「' || v_sup_lot || '」は既に使用期限 ' || v_lot.expires_on || ' で登録されています。使用期限を確認してください。');
    end if;
    if v_lot.status = 'VOID' then
      perform exo.set_lot_status(v_lot.id, 'QUARANTINE', '再入荷', v_user);
    elsif v_lot.status <> 'QUARANTINE' then
      perform exo.fail('ロット「' || v_lot.lot_no || '」は' || exo.code_label('lot_status', v_lot.status) || 'のため、簡易版では追加入荷できません。' ||
        '（合格済ロットへの分納はQA確認が必要です。仕入先に確認のうえ別の仕入先ロット番号で登録してください）');
    end if;
    select coalesce(sum(on_hand_qty), 0) into v_stock from exo.t_inventory where lot_id = v_lot.id;
    update exo.t_lot set unit_cost = round((v_stock * unit_cost + v_qty * v_price) / (v_stock + v_qty), 2) where id = v_lot.id;
  else
    v_head := v_product.product_code || '-' || to_char(v_date, 'YYMMDD') || '-';
    insert into exo.t_lot (lot_no, product_id, supplier_id, supplier_lot_no, manufactured_on, expires_on, received_on, unit_cost, status)
    values (v_head || lpad((coalesce((select max(substr(lot_no, length(v_head) + 1)::integer) from exo.t_lot
                                      where left(lot_no, length(v_head)) = v_head and substr(lot_no, length(v_head) + 1) ~ '^\d{1,9}$'), 0) + 1)::text, 2, '0'),
      v_product.id, v_supplier.id, v_sup_lot, v_mfg, v_exp, v_date, v_price, 'QUARANTINE')
    returning * into v_lot;
    insert into exo.t_lot_status_history (lot_id, from_status, to_status, reason, changed_by)
    values (v_lot.id, null, 'QUARANTINE', '入荷', v_user);
  end if;

  v_receipt_no := exo.next_no('RC', v_date, array(select receipt_no from exo.t_receipt));
  insert into exo.t_receipt (receipt_no, supplier_id, receipt_date, product_id, supplier_lot_no, manufactured_on, expires_on,
    arrival_temp, location_id, quantity, unit_price, lot_id, created_by)
  values (v_receipt_no, v_supplier.id, v_date, v_product.id, v_sup_lot, v_mfg, v_exp, v_temp, v_loc.id, v_qty, v_price, v_lot.id, v_user)
  returning id into v_receipt_id;
  perform exo.move('RECEIPT', v_lot.id, v_loc.id, v_qty, 'receipt', v_receipt_id, null, v_user);

  if v_temp is not null and (v_temp < v_loc.temp_min or v_temp > v_loc.temp_max) then
    v_warning := '到着時温度が許容範囲（' || v_loc.temp_min || '〜' || v_loc.temp_max || '℃）外です。検品時にQAが評価してください。';
  end if;
  return jsonb_build_object('receiptNo', v_receipt_no, 'lotNo', v_lot.lot_no, 'warning', v_warning);
end $$;

/** ロットステータス変更（受入検品 P-02 と QA によるステータス変更 P-15）。p = { lotId, to, reason, coaConfirmed } */
create or replace function public.change_lot_status(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_user text := exo.require_user();
  v_lot exo.t_lot;
  v_to text := exo.j_text(p, 'to');
  v_reason text := exo.j_text(p, 'reason');
  v_allowed jsonb := '{"QUARANTINE": ["RELEASED", "REJECTED", "HOLD"], "RELEASED": ["HOLD"], "HOLD": ["RELEASED", "QUARANTINE", "REJECTED"]}';
begin
  perform exo.write_lock();
  select * into v_lot from exo.t_lot where id = exo.j_id(p, 'lotId') for update;
  if v_lot.id is null then perform exo.fail('ロットが見つかりません。画面を再読込してください。'); end if;
  if v_to is null or not coalesce(v_allowed -> v_lot.status ? v_to, false) then
    perform exo.fail('現在のステータス（' || exo.code_label('lot_status', v_lot.status) || '）から「' ||
      coalesce(exo.code_label('lot_status', v_to), '') || '」には変更できません。');
  end if;
  if v_to = 'RELEASED' then
    if not exo.j_bool(p, 'coaConfirmed') then perform exo.fail('合格にはCOA（試験成績書）の確認が必要です（BR-08）。'); end if;
    if v_lot.status = 'HOLD' and v_lot.inspected_at is null then
      perform exo.fail('未検品のロットは「検品待ち」に戻してから検品してください（BR-17）。');
    end if;
    if v_lot.status = 'HOLD' and v_reason is null then perform exo.fail('保留解除の理由を入力してください。'); end if;
    if v_lot.expires_on < exo.today() then perform exo.fail('使用期限を過ぎたロットは合格にできません。'); end if;
  elsif v_reason is null then
    perform exo.fail('理由を入力してください。');
  end if;
  if v_lot.status = 'HOLD' and v_to = 'QUARANTINE' and v_lot.inspected_at is not null then
    perform exo.fail('検品済のロットは「合格」または「不合格」に変更してください。');
  end if;
  if v_lot.status = 'QUARANTINE' then
    update exo.t_lot set inspected_by = v_user, inspected_at = now() where id = v_lot.id;
  end if;
  perform exo.set_lot_status(v_lot.id, v_to, coalesce(v_reason, '検品合格（COA確認済）'), v_user);
  return exo.lot_view(v_lot.id);
end $$;

-- ---- 出荷（P-04 FEFO自動引当 ＋ P-05 出荷確定 を同時に実行） ----

/**
 * p = { customerId, shippedOn, note, lines: [{ productId, quantity, unitPrice }] }
 * 全明細の在庫が揃わない場合は何も登録しない（全量引当できたときだけ確定）。
 */
create or replace function public.create_shipment(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_user text := exo.require_user();
  v_customer exo.m_customer;
  v_product exo.m_product;
  v_shipped_on date := exo.to_date(exo.j_text(p, 'shippedOn'));
  v_lines jsonb := '[]';
  v_line jsonb;
  v_qty integer;
  v_price numeric;
  v_remain integer;
  v_take integer;
  v_avail integer;
  v_used jsonb := '{}';   -- 同一出荷内で既に割り当てた数量（在庫行ID → 数量）
  v_plan jsonb := '[]';
  v_i integer := 0;
  v_shipment_id bigint;
  v_line_id bigint;
  c record;
  a jsonb;
begin
  perform exo.write_lock();
  select * into v_customer from exo.m_customer where id = exo.j_id(p, 'customerId');
  if v_customer.id is null then perform exo.fail('顧客が見つかりません。画面を再読込してください。'); end if;
  if not v_customer.is_active then perform exo.fail('無効な顧客には出荷できません。'); end if;
  if v_shipped_on is null then perform exo.fail('出荷日を入力してください。'); end if;
  if jsonb_typeof(p -> 'lines') = 'array' then
    select coalesce(jsonb_agg(x order by o), '[]') into v_lines
    from jsonb_array_elements(p -> 'lines') with ordinality as e(x, o)
    where jsonb_typeof(x) = 'object' and exo.j_text(x, 'productId') is not null;
  end if;
  if jsonb_array_length(v_lines) = 0 then perform exo.fail('出荷明細を1行以上入力してください。'); end if;
  if jsonb_array_length(v_lines) > 100 then perform exo.fail('出荷明細は100行以内にしてください。'); end if;

  for v_line in select x from jsonb_array_elements(v_lines) x loop
    v_i := v_i + 1;
    select * into v_product from exo.m_product where id = exo.j_id(v_line, 'productId');
    if v_product.id is null then perform exo.fail('商品が見つかりません。画面を再読込してください。'); end if;
    if not v_product.is_active then perform exo.fail('商品「' || v_product.name || '」は無効化されています。'); end if;
    v_qty := exo.pos_int(exo.j_num(v_line, 'quantity'), v_i || '行目の数量');
    v_price := coalesce(exo.j_num(v_line, 'unitPrice'), v_product.list_price, 0);
    if v_price = 'NaN' or v_price < 0 or v_price >= 1000000000000 then perform exo.fail(v_i || '行目の単価が不正です。'); end if;
    v_price := round(v_price, 2);
    if not exists (select 1 from exo.m_sales_rule r where r.regulatory_class = v_product.regulatory_class
                   and r.customer_type = v_customer.customer_type and r.allowed) then
      perform exo.fail('商品「' || v_product.name || '」（' || exo.code_label('regulatory_class', v_product.regulatory_class) ||
        '）は顧客区分「' || exo.code_label('customer_type', v_customer.customer_type) || '」に販売できません（BR-09）。');
    end if;
    -- BR-04 引当可能在庫 → BR-05 FEFO（使用期限→入荷日→保管場所）
    v_remain := v_qty;
    for c in
      select i.id as inv_id, i.on_hand_qty, l.id as lot_id, l.unit_cost, loc.id as loc_id
      from exo.t_inventory i
      join exo.t_lot l on l.id = i.lot_id
      join exo.m_location loc on loc.id = i.location_id
      where l.product_id = v_product.id and l.status = 'RELEASED' and not loc.is_quarantine and i.on_hand_qty > 0
        and l.expires_on - v_shipped_on >= v_product.min_remaining_days
      order by l.expires_on, l.received_on, loc.id, l.id
      for update of i
    loop
      exit when v_remain <= 0;
      v_avail := c.on_hand_qty - coalesce((v_used ->> c.inv_id::text)::integer, 0);
      continue when v_avail <= 0;
      v_take := least(v_remain, v_avail);
      v_used := jsonb_set(v_used, array[c.inv_id::text], to_jsonb(coalesce((v_used ->> c.inv_id::text)::integer, 0) + v_take));
      v_plan := v_plan || jsonb_build_array(jsonb_build_object('product_id', v_product.id, 'lot_id', c.lot_id, 'loc_id', c.loc_id,
        'qty', v_take, 'price', v_price, 'cost', c.unit_cost));
      v_remain := v_remain - v_take;
    end loop;
    if v_remain > 0 then
      perform exo.fail('商品「' || v_product.name || '」の引当可能在庫が不足しています（不足 ' || v_remain || '）。' ||
        '合格済・残期間 ' || v_product.min_remaining_days || '日以上・隔離保管場所以外の在庫のみ引当できます。');
    end if;
  end loop;

  insert into exo.t_shipment (shipment_no, customer_id, shipped_on, status, note, created_by)
  values (exo.next_no('SH', v_shipped_on, array(select shipment_no from exo.t_shipment)), v_customer.id, v_shipped_on, 'SHIPPED',
    left(exo.j_text(p, 'note'), 1000), v_user)
  returning id into v_shipment_id;
  for a in select x from jsonb_array_elements(v_plan) x loop
    insert into exo.t_shipment_line (shipment_id, product_id, lot_id, location_id, quantity, unit_price, unit_cost, status)
    values (v_shipment_id, (a ->> 'product_id')::bigint, (a ->> 'lot_id')::bigint, (a ->> 'loc_id')::bigint, (a ->> 'qty')::integer,
      (a ->> 'price')::numeric, (a ->> 'cost')::numeric, 'SHIPPED')
    returning id into v_line_id;
    perform exo.move('SHIPMENT', (a ->> 'lot_id')::bigint, (a ->> 'loc_id')::bigint, -(a ->> 'qty')::integer, 'shipment_line', v_line_id, null, v_user);
  end loop;
  return exo.shipment_view(v_shipment_id);
end $$;

/** 出荷取消（P-06）：赤伝で在庫を戻す。返品がある出荷は取消不可。p = { shipmentId, reason } */
create or replace function public.cancel_shipment(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_user text := exo.require_user();
  v_ship exo.t_shipment;
  v_reason text := exo.j_text(p, 'reason');
  l record;
  v_recall bigint;
begin
  perform exo.write_lock();
  select * into v_ship from exo.t_shipment where id = exo.j_id(p, 'shipmentId') for update;
  if v_ship.id is null then perform exo.fail('出荷が見つかりません。画面を再読込してください。'); end if;
  if v_ship.status <> 'SHIPPED' then perform exo.fail('この出荷は既に取消されています。'); end if;
  if v_reason is null then perform exo.fail('取消理由を入力してください。'); end if;
  if exists (select 1 from exo.t_shipment_line sl join exo.t_return r on r.shipment_line_id = sl.id where sl.shipment_id = v_ship.id) then
    perform exo.fail('返品が登録されている出荷は取消できません。');
  end if;
  for l in select * from exo.t_shipment_line where shipment_id = v_ship.id and status = 'SHIPPED' order by id loop
    perform exo.move('CANCEL', l.lot_id, l.location_id, l.quantity, 'shipment_line', l.id, v_reason, v_user);
    update exo.t_shipment_line set status = 'CANCELLED' where id = l.id;
  end loop;
  update exo.t_shipment set status = 'CANCELLED', note = coalesce(note || ' / ', '') || '取消：' || v_reason where id = v_ship.id;
  for v_recall in select distinct x from exo.t_shipment_line sl, exo.open_recall_ids(sl.lot_id) x where sl.shipment_id = v_ship.id loop
    perform exo.extract_targets(v_recall);
  end loop;
  return exo.shipment_view(v_ship.id);
end $$;

-- ---- 返品（P-07 の簡易版：登録と処置判定を同時に行う） ----

/**
 * p = { shipmentLineId, quantity, reason, returnedOn, quarantineLocationId, disposition: 'RESTOCK'|'DISPOSE', restockLocationId }
 * 回収中ロットの返品は自動的に回収品として扱い、処置は廃棄のみ（BR-18）。
 */
create or replace function public.register_return(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_user text := exo.require_user();
  v_line exo.t_shipment_line;
  v_ship exo.t_shipment;
  v_lot exo.t_lot;
  v_product exo.m_product;
  v_qloc exo.m_location;
  v_rloc exo.m_location;
  v_qty integer;
  v_returnable integer;
  v_reason text := exo.j_text(p, 'reason');
  v_returned_on date;
  v_target exo.t_recall_target;
  v_disp text := exo.j_text(p, 'disposition');
  v_return_id bigint;
  v_return_no text;
  v_recovered integer;
  v_recall bigint;
begin
  perform exo.write_lock();
  select * into v_line from exo.t_shipment_line where id = exo.j_id(p, 'shipmentLineId') for update;
  if v_line.id is null then perform exo.fail('出荷明細が見つかりません。画面を再読込してください。'); end if;
  if v_line.status <> 'SHIPPED' then perform exo.fail('取消済の出荷明細には返品を登録できません。'); end if;
  select * into v_ship from exo.t_shipment where id = v_line.shipment_id;
  select * into v_lot from exo.t_lot where id = v_line.lot_id;
  select * into v_product from exo.m_product where id = v_line.product_id;
  v_qty := exo.pos_int(exo.j_num(p, 'quantity'), '返品数量');
  v_returnable := v_line.quantity - exo.returned_qty(v_line.id);
  if v_qty > v_returnable then perform exo.fail('返品数量が返品可能数（' || v_returnable || '）を超えています（BR-12）。'); end if;
  if v_reason is null then perform exo.fail('返品理由を入力してください。'); end if;
  if exo.j_text(p, 'returnedOn') is null then
    v_returned_on := exo.today();
  else
    v_returned_on := exo.to_date(exo.j_text(p, 'returnedOn'));
    if v_returned_on is null then perform exo.fail('返品日が不正です。'); end if;
  end if;
  if v_returned_on < v_ship.shipped_on or v_returned_on > exo.today() then
    perform exo.fail('返品日は出荷日（' || v_ship.shipped_on || '）以降、当日以前の日付を入力してください。');
  end if;
  select * into v_qloc from exo.m_location where id = exo.j_id(p, 'quarantineLocationId');
  if v_qloc.id is null then perform exo.fail('受入保管場所が見つかりません。画面を再読込してください。'); end if;
  if not v_qloc.is_quarantine or v_qloc.storage_class <> v_product.storage_class or not v_qloc.is_active then
    perform exo.fail('受入保管場所は、商品と同じ温度区分の隔離保管場所を選択してください。');
  end if;

  -- 回収中ロットなら回収対象に紐づける（P-07 ステップ2）
  select t.* into v_target from exo.t_recall_target t
  where t.recall_id in (select exo.open_recall_ids(v_lot.id)) and t.customer_id = v_ship.customer_id and t.lot_id = v_lot.id
  order by t.recall_id limit 1 for update;
  if v_target.id is not null then v_disp := 'DISPOSE'; end if;
  if v_disp is null or v_disp not in ('RESTOCK', 'DISPOSE') then perform exo.fail('処置（在庫戻し／廃棄）を選択してください。'); end if;
  if v_disp = 'RESTOCK' then
    if v_lot.status <> 'RELEASED' then
      perform exo.fail('ロットが合格（RELEASED）ではないため在庫に戻せません。廃棄を選択してください。');
    end if;
    select * into v_rloc from exo.m_location where id = exo.j_id(p, 'restockLocationId');
    if v_rloc.id is null then perform exo.fail('戻し保管場所が見つかりません。画面を再読込してください。'); end if;
    if v_rloc.is_quarantine or v_rloc.storage_class <> v_product.storage_class or not v_rloc.is_active then
      perform exo.fail('戻し保管場所は、商品と同じ温度区分の通常保管場所を選択してください。');
    end if;
  end if;

  v_return_no := exo.next_no('RT', v_returned_on, array(select return_no from exo.t_return));
  insert into exo.t_return (return_no, shipment_line_id, recall_target_id, returned_on, quantity, reason, disposition,
    location_id, restock_location_id, created_by)
  values (v_return_no, v_line.id, v_target.id, v_returned_on, v_qty, v_reason, v_disp, v_qloc.id, v_rloc.id, v_user)
  returning id into v_return_id;
  perform exo.move('RETURN', v_lot.id, v_qloc.id, v_qty, 'return', v_return_id, null, v_user);
  if v_disp = 'RESTOCK' then
    perform exo.move('TRANSFER_OUT', v_lot.id, v_qloc.id, -v_qty, 'return', v_return_id, null, v_user);
    perform exo.move('TRANSFER_IN', v_lot.id, v_rloc.id, v_qty, 'return', v_return_id, null, v_user);
  else
    perform exo.move('DISPOSE', v_lot.id, v_qloc.id, -v_qty, 'return', v_return_id, '返品廃棄：' || v_reason, v_user);
  end if;

  if v_target.id is not null then
    select coalesce(sum(quantity), 0) into v_recovered from exo.t_return where recall_target_id = v_target.id;
    update exo.t_recall_target set recovered_qty = v_recovered,
      unrecoverable_qty = least(unrecoverable_qty, greatest(shipped_qty - v_recovered, 0)),
      status = case when status <> 'CLOSED' and v_recovered + least(unrecoverable_qty, greatest(shipped_qty - v_recovered, 0)) >= shipped_qty
                    then 'RECOVERED' else status end,
      updated_at = now()
    where id = v_target.id;
  else
    for v_recall in select exo.open_recall_ids(v_lot.id) loop
      perform exo.extract_targets(v_recall);
    end loop;
  end if;
  return jsonb_build_object('returnNo', v_return_no, 'recall', v_target.id is not null, 'disposition', v_disp);
end $$;

-- ---- トレース（SQL-01 / SQL-02 相当） ----

/** ロット番号（社内・仕入先どちらでも、部分一致）→ 出荷先顧客。p = { query } */
create or replace function public.trace_lot(p jsonb default '{}') returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_q text := upper(coalesce(exo.j_text(p, 'query'), ''));
begin
  perform exo.require_user();
  if v_q = '' then perform exo.fail('ロット番号を入力してください。'); end if;
  return coalesce((
    select jsonb_agg(v.j || jsonb_build_object(
      'inventory', coalesce((select jsonb_agg(jsonb_build_object('location', loc.name, 'qty', i.on_hand_qty) order by loc.id)
                             from exo.t_inventory i join exo.m_location loc on loc.id = i.location_id
                             where i.lot_id = l.id and i.on_hand_qty <> 0), '[]'),
      'shipments', coalesce((select jsonb_agg(jsonb_build_object(
                               'customer_code', c.customer_code, 'customer', c.name, 'phone', c.phone, 'email', c.email,
                               'shipment_no', s.shipment_no, 'shipped_on', s.shipped_on, 'status', sl.status, 'quantity', sl.quantity,
                               'returned', exo.returned_qty(sl.id, false), 'recalled', exo.returned_qty(sl.id, true),
                               'net', case when sl.status = 'SHIPPED' then sl.quantity - exo.returned_qty(sl.id) else 0 end)
                             order by s.shipped_on, sl.id)
                             from exo.t_shipment_line sl
                             join exo.t_shipment s on s.id = sl.shipment_id
                             join exo.m_customer c on c.id = s.customer_id
                             where sl.lot_id = l.id), '[]'),
      'movementTotals', coalesce((select jsonb_object_agg(m.movement_type, m.total)
                                  from (select movement_type, sum(quantity) as total from exo.t_stock_movement
                                        where lot_id = l.id group by movement_type) m), '{}'),
      'history', coalesce((select jsonb_agg(jsonb_build_object('id', h.id, 'from_status', h.from_status, 'to_status', h.to_status,
                             'reason', h.reason, 'changed_at', exo.fmt_ts(h.changed_at), 'changed_by', h.changed_by) order by h.id)
                           from exo.t_lot_status_history h where h.lot_id = l.id), '[]'))
      order by l.id)
    from (select * from exo.t_lot
          where strpos(upper(lot_no), v_q) > 0 or strpos(upper(supplier_lot_no), v_q) > 0
          order by id limit 20) l
    join exo.v_lot v on v.id = l.id), '[]');
end $$;

/** 顧客 → 購入ロット。p = { customerId, from, to } */
create or replace function public.trace_customer(p jsonb default '{}') returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_customer exo.m_customer;
  v_from date := exo.to_date(exo.j_text(p, 'from'));
  v_to date := exo.to_date(exo.j_text(p, 'to'));
begin
  perform exo.require_user();
  select * into v_customer from exo.m_customer where id = exo.j_id(p, 'customerId');
  if v_customer.id is null then perform exo.fail('顧客を選択してください。'); end if;
  if (exo.j_text(p, 'from') is not null and v_from is null) or (exo.j_text(p, 'to') is not null and v_to is null) then
    perform exo.fail('期間の日付が不正です。');
  end if;
  return jsonb_build_object(
    'customer', to_jsonb(v_customer) - 'created_at' - 'updated_at',
    'rows', coalesce((select jsonb_agg(jsonb_build_object(
        'shipped_on', s.shipped_on, 'shipment_no', s.shipment_no, 'product', pr.name, 'lot_no', l.lot_no,
        'supplier_lot_no', l.supplier_lot_no, 'expires_on', l.expires_on, 'lot_status', l.status,
        'lot_status_label', exo.code_label('lot_status', l.status), 'quantity', sl.quantity,
        'returned', exo.returned_qty(sl.id), 'net', sl.quantity - exo.returned_qty(sl.id))
        order by s.shipped_on desc, s.id desc, sl.id)
      from exo.t_shipment s
      join exo.t_shipment_line sl on sl.shipment_id = s.id
      join exo.t_lot l on l.id = sl.lot_id
      join exo.m_product pr on pr.id = sl.product_id
      where s.customer_id = v_customer.id and s.status = 'SHIPPED' and sl.status = 'SHIPPED'
        and (v_from is null or s.shipped_on >= v_from) and (v_to is null or s.shipped_on <= v_to)), '[]'));
end $$;

-- ---- 回収（P-08 / P-14 / P-18 / P-19 の簡易版） ----

/** p = { title, reason, severity, lotIds: [] } */
create or replace function public.create_recall(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_user text := exo.require_user();
  v_title text := exo.j_text(p, 'title');
  v_reason text := exo.j_text(p, 'reason');
  v_severity text := exo.j_text(p, 'severity');
  v_ids bigint[];
  v_today date := exo.today();
  v_recall_id bigint;
  v_recall_no text;
  l record;
begin
  perform exo.write_lock();
  if v_title is null or v_reason is null then perform exo.fail('件名と回収理由は必須です。'); end if;
  if v_severity is null or v_severity not in ('I', 'II', 'III') then perform exo.fail('重大度（クラスI/II/III）を選択してください。'); end if;
  if jsonb_typeof(p -> 'lotIds') = 'array' then
    select array_agg(distinct exo.j_id(jsonb_build_object('v', x), 'v')) into v_ids
    from jsonb_array_elements(p -> 'lotIds') x where exo.trim_text(x #>> '{}') is not null;
  end if;
  if v_ids is null or cardinality(v_ids) = 0 then perform exo.fail('対象ロットを1件以上選択してください。'); end if;
  if array_position(v_ids, null) is not null or (select count(*) from exo.t_lot where id = any (v_ids)) <> cardinality(v_ids) then
    perform exo.fail('ロットが見つかりません。画面を再読込してください。');
  end if;
  if exists (select 1 from exo.t_lot where id = any (v_ids) and status = 'VOID') then
    perform exo.fail('無効（VOID）のロットは回収対象に指定できません。');
  end if;
  v_recall_no := 'RCL-' || to_char(v_today, 'YYYY') || '-' || lpad((coalesce((select max(substr(recall_no, 10)::integer) from exo.t_recall
    where recall_no like 'RCL-' || to_char(v_today, 'YYYY') || '-%' and substr(recall_no, 10) ~ '^\d{1,9}$'), 0) + 1)::text, 3, '0');
  insert into exo.t_recall (recall_no, title, reason, severity, started_on, status, created_by)
  values (v_recall_no, v_title, v_reason, v_severity, v_today, 'OPEN', v_user)
  returning id into v_recall_id;
  for l in select id, status from exo.t_lot where id = any (v_ids) order by id for update loop
    insert into exo.t_recall_lot (recall_id, lot_id) values (v_recall_id, l.id);
    if l.status <> 'RECALLED' then
      perform exo.set_lot_status(l.id, 'RECALLED', '回収 ' || v_recall_no || '：' || v_reason, v_user);
    end if;
  end loop;
  perform exo.extract_targets(v_recall_id);
  return exo.recall_view(v_recall_id);
end $$;

create or replace function public.list_recalls(p jsonb default '{}') returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  perform exo.require_user();
  return coalesce((select jsonb_agg(exo.recall_view(id) order by id desc) from exo.t_recall), '[]');
end $$;

/** p = { recallId } */
create or replace function public.reextract_recall(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare v_recall exo.t_recall;
begin
  perform exo.require_user();
  perform exo.write_lock();
  select * into v_recall from exo.t_recall where id = exo.j_id(p, 'recallId');
  if v_recall.id is null then perform exo.fail('回収案件が見つかりません。画面を再読込してください。'); end if;
  if v_recall.status = 'CLOSED' then perform exo.fail('完了した回収案件です。'); end if;
  perform exo.extract_targets(v_recall.id);
  return exo.recall_view(v_recall.id);
end $$;

/** p = { targetId, contactedOn, contactMethod, status: 'CONTACTED'|'CLOSED'|'', unrecoverableQty, closeReason } */
create or replace function public.update_recall_target(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_t exo.t_recall_target;
  v_recall_status text;
  v_contacted date;
  v_unrec numeric;
  v_status text;
  v_close text := exo.j_text(p, 'closeReason');
begin
  perform exo.require_user();
  perform exo.write_lock();
  select * into v_t from exo.t_recall_target where id = exo.j_id(p, 'targetId') for update;
  if v_t.id is null then perform exo.fail('回収対象が見つかりません。画面を再読込してください。'); end if;
  select status into v_recall_status from exo.t_recall where id = v_t.recall_id;
  if v_recall_status = 'CLOSED' then perform exo.fail('完了した回収案件は更新できません。'); end if;
  if p ? 'contactedOn' then
    v_contacted := exo.to_date(exo.j_text(p, 'contactedOn'));
    if exo.j_text(p, 'contactedOn') is not null and (v_contacted is null or v_contacted > exo.today()) then
      perform exo.fail('連絡日が不正です（当日以前の日付を入力してください）。');
    end if;
    v_t.contacted_on := v_contacted;
  end if;
  if p ? 'contactMethod' then v_t.contact_method := left(exo.j_text(p, 'contactMethod'), 50); end if;
  if exo.j_text(p, 'unrecoverableQty') is not null then
    v_unrec := exo.j_num(p, 'unrecoverableQty');
    if v_unrec = 'NaN' or v_unrec < 0 or v_unrec <> trunc(v_unrec) or v_unrec > 1000000000 then
      perform exo.fail('回収不能数量は0以上の整数で入力してください。');
    end if;
    if v_unrec + v_t.recovered_qty > v_t.shipped_qty then perform exo.fail('回収数量＋回収不能数量が出荷正味数量を超えています。'); end if;
    v_t.unrecoverable_qty := v_unrec;
  end if;
  v_status := exo.j_text(p, 'status');
  if v_status = 'CLOSED' then
    if v_close is null then perform exo.fail('クローズ理由を入力してください。'); end if;
    v_t.status := 'CLOSED';
    v_t.close_reason := left(v_close, 500);
  elsif v_status = 'CONTACTED' and v_t.status = 'NOT_CONTACTED' then
    v_t.status := 'CONTACTED';
  elsif v_status is not null and v_status not in ('CONTACTED', 'CLOSED') then
    perform exo.fail('状態が不正です。');
  end if;
  if v_t.status <> 'CLOSED' then
    if v_t.shipped_qty > 0 and v_t.recovered_qty + v_t.unrecoverable_qty >= v_t.shipped_qty then
      v_t.status := 'RECOVERED';
    elsif v_t.status = 'RECOVERED' then
      v_t.status := case when v_t.contacted_on is not null then 'CONTACTED' else 'NOT_CONTACTED' end;
    end if;
  end if;
  update exo.t_recall_target set contacted_on = v_t.contacted_on, contact_method = v_t.contact_method,
    unrecoverable_qty = v_t.unrecoverable_qty, status = v_t.status, close_reason = v_t.close_reason, updated_at = now()
  where id = v_t.id;
  return exo.recall_view(v_t.recall_id);
end $$;

/** p = { recallId } */
create or replace function public.close_recall(p jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_recall exo.t_recall;
  v_open integer;
  v_view jsonb;
begin
  perform exo.require_user();
  perform exo.write_lock();
  select * into v_recall from exo.t_recall where id = exo.j_id(p, 'recallId') for update;
  if v_recall.id is null then perform exo.fail('回収案件が見つかりません。画面を再読込してください。'); end if;
  if v_recall.status = 'CLOSED' then perform exo.fail('既に完了しています。'); end if;
  select count(*) into v_open from exo.t_recall_target where recall_id = v_recall.id and status not in ('RECOVERED', 'CLOSED');
  if v_open > 0 then perform exo.fail('未完了の回収対象顧客が ' || v_open || ' 件あるため完了できません。'); end if;
  update exo.t_recall set status = 'CLOSED', closed_on = exo.today() where id = v_recall.id;
  v_view := exo.recall_view(v_recall.id);
  return v_view || jsonb_build_object('warning', case when (v_view ->> 'remainingStock')::integer > 0
    then '回収対象ロットに未処分の在庫（' || (v_view ->> 'remainingStock') || '）が残っています。' else '' end);
end $$;

-- -----------------------------------------------------------------------------
-- 権限：画面用関数はログイン済み（authenticated）のみ実行可。未ログイン（anon）は不可
-- -----------------------------------------------------------------------------
do $$
declare f text;
begin
  foreach f in array array['get_config', 'get_masters', 'get_dashboard', 'get_lots', 'get_inventory', 'get_recent_shipments',
    'get_shipment_by_no', 'save_master', 'save_sales_rule', 'register_receipt', 'change_lot_status', 'create_shipment',
    'cancel_shipment', 'register_return', 'trace_lot', 'trace_customer', 'create_recall', 'list_recalls', 'reextract_recall',
    'update_recall_target', 'close_recall']
  loop
    execute format('revoke all on function public.%I(jsonb) from public', f);
    execute format('revoke all on function public.%I(jsonb) from anon', f);
    execute format('grant execute on function public.%I(jsonb) to authenticated', f);
  end loop;
end $$;
revoke all on all tables in schema exo from anon, authenticated;
revoke all on all sequences in schema exo from anon, authenticated;
revoke all on all functions in schema exo from anon, authenticated;
revoke all on schema exo from anon, authenticated;

-- -----------------------------------------------------------------------------
-- 初期データ（空のときだけ投入。何度実行しても重複しない）
-- -----------------------------------------------------------------------------
insert into exo.m_location (location_code, name, storage_class, temp_min, temp_max, is_quarantine)
select * from (values
  ('L-M80-01', '-80℃冷凍庫#1', 'M80', -90, -60, false),
  ('Q-M80-01', '-80℃隔離庫（返品・保留）', 'M80', -90, -60, true),
  ('L-COLD-01', '2-8℃冷蔵庫#1', 'COLD', 2, 8, false),
  ('Q-COLD-01', '2-8℃隔離庫（返品・保留）', 'COLD', 2, 8, true)) v
where not exists (select 1 from exo.m_location);

-- 初期値は仮設定。法的区分の確認（設計書 課題 Q-01）後に「マスタ」画面で必ず見直すこと
insert into exo.m_sales_rule (regulatory_class, customer_type, allowed)
select rc, ct, (rc, ct) in (('COSMETIC_RAW', 'MEDICAL'), ('COSMETIC_RAW', 'SALON'), ('COSMETIC_RAW', 'DISTRIBUTOR'),
                            ('RESEARCH_USE', 'RESEARCH'), ('MEDICAL_USE', 'MEDICAL'))
from unnest(array['COSMETIC_RAW', 'RESEARCH_USE', 'MEDICAL_USE', 'OTHER']) rc,
     unnest(array['MEDICAL', 'SALON', 'DISTRIBUTOR', 'RESEARCH', 'OTHER']) ct
on conflict (regulatory_class, customer_type) do nothing;

-- -----------------------------------------------------------------------------
-- 日次チェックの自動実行（pg_cron。毎日 1:00 日本時間 = 16:00 UTC）
--   pg_cron が使えない環境ではスキップする（画面の動作には影響しない）
-- -----------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron with schema pg_catalog;
    perform cron.schedule('exo-trace-daily-check', '0 16 * * *', 'select exo.daily_check()');
  else
    raise notice 'pg_cron が無いため日次チェックの自動実行は設定しませんでした。';
  end if;
exception when others then
  raise notice '日次チェックの自動実行を設定できませんでした: %', sqlerrm;
end $$;
